Update hook scripts for the RevtreePlugin/LogEnhancer
git-svn-id: https://trac-hacks.org/svn@3581 7322e99d-02ea-0310-aa39-e9a107903beb

diff --git a/revtreeplugin/0.11/hooks/svnstubs/post-commit b/revtreeplugin/0.11/hooks/svnstubs/post-commit
--- a/revtreeplugin/0.11/hooks/svnstubs/post-commit
+++ b/revtreeplugin/0.11/hooks/svnstubs/post-commit
@@ -1,32 +1,27 @@
 #!/bin/sh
 
-# POST-COMMIT HOOK
-#
-#   [1] REPOS-PATH   (the path to this repository)
-#   [2] TRANSACTION  (the transaction being processed)
-
 REPOS="$1"
 REV="$2"
-CONFIG_PATH=`dirname $0`
 
-# Load global config
-if [ -f "${CONFIG_PATH}/config" ]; then
-  . ${CONFIG_PATH}/config
+SELF=`readlink -f $0`
+CONF=`dirname ${SELF}`/hook.conf
+if [ -f ${CONF} ]; then
+    . ${CONF}
 else
-  echo "Missing config file" >&2
+    echo "Missing hook configuration file" >&2
+    exit -1
 fi
 
-REPOSNAME=`echo "$REPOS" | sed -r 's/^.*\/([^\/]+)$/\1/'`
-TRAC_ENV="${TRAC_ENV_PARENT_DIR}/${REPOSNAME}"
-LOGFILE="${TRAC_ENV}/log/svn-postcommit.log"
-
-export PYTHONPATH=$TRACPATH
+export PYTHONPATH=$TRACPATH:$GENSHIPATH
+export PYTHON_EGG_CACHE
+export PYTHON=`which python2.5`
 date >> "$LOGFILE"
 echo "Revision: $REV" >> "$LOGFILE"
-${PYTHON} ${TRAC_PATH}/hooks/trac-commit-hook \
-    -d "$REPOS" -r "$REV" -p "$TRAC_ENV" 2>> "$LOGFILE"
+${PYTHON} ${HOOKPATH}/trac-commit-hook -d "$REPOS" -r "$REV" -p "$TRAC_ENV" \
+     2>> "$LOGFILE"
 if [ $? -ne 0 ]; then
-  if [ -n ${MAIL_ADMIN} ];
-    tail -5 "$LOGFILE" | mail ${MAIL_ADMIN} \
-      -s "[${REPOSNAME}] Unable to post-commit revision ${REV}"
+    tail -5 "$LOGFILE" | \
+      cat
+      #mail admin -s "[${REPOSNAME}] Unable to post-commit revision ${REV}"
 fi
+
diff --git a/revtreeplugin/0.11/hooks/svnstubs/post-revprop-change b/revtreeplugin/0.11/hooks/svnstubs/post-revprop-change
--- a/revtreeplugin/0.11/hooks/svnstubs/post-revprop-change
+++ b/revtreeplugin/0.11/hooks/svnstubs/post-revprop-change
@@ -16,22 +16,22 @@ REV="$2"
 USER="$3"
 PROPNAME="$4"
 ACTION="$5"
-CONFIG_PATH=`dirname $0`
 
-if [ -f "${CONFIG_PATH}/config" ]; then
-  . ${CONFIG_PATH}/config
+SELF=`readlink -f $0`
+CONF=`dirname ${SELF}`/hook.conf
+if [ -f ${CONF} ]; then
+    . ${CONF}
 else
-  echo "Missing config file" >&2
+    echo "Missing hook configuration file" >&2
+    exit -1
 fi
 
-REPOSNAME=`echo "$REPOS" | sed -r 's/^.*\/([^\/]+)$/\1/'`
-TRAC_ENV="${TRAC_ENV_PARENT_DIR}/${REPOSNAME}"
-LOGFILE="${TRAC_ENV}/log/svn-postrevpropchange.log"
-
-export PYTHONPATH=$TRACPATH
+export PYTHONPATH=$TRACPATH:$GENSHIPATH
+export PYTHON_EGG_CACHE
+export PYTHON=`which python2.5`
 date >> "$LOGFILE"
 echo "Revprop: $REV $PROPNAME" >> $LOGFILE
-${PYTHON} ${TRACPATH}/hooks/trac-revprop-hook -p "$TRAC_ENV" -u "$USER" \
+${PYTHON} ${HOOKPATH}/trac-revprop-hook -p "$TRAC_ENV" -u "$USER" \
     -n "$PROPNAME" -d "$REPOS" -r "$REV" -a "$ACTION" post 2>> "$LOGFILE"
 if [ $? -ne 0 ]; then
     tail -5 "$LOGFILE" | \
diff --git a/revtreeplugin/0.11/hooks/svnstubs/pre-commit b/revtreeplugin/0.11/hooks/svnstubs/pre-commit
--- a/revtreeplugin/0.11/hooks/svnstubs/pre-commit
+++ b/revtreeplugin/0.11/hooks/svnstubs/pre-commit
@@ -1,28 +1,22 @@
 #!/bin/sh
 
-# PRE-COMMIT HOOK
-#
-#   [1] REPOS-PATH   (the path to this repository)
-#   [2] TRANSACTION  (the transaction being processed)
-
 REPOS="$1"
 TXN="$2"
-CONFIG_PATH=`dirname $0`
 
-if [ -f "${CONFIG_PATH}/config" ]; then
-  . ${CONFIG_PATH}/config
+SELF=`readlink -f $0`
+CONF=`dirname ${SELF}`/hook.conf
+if [ -f ${CONF} ]; then
+    . ${CONF}
 else
-  echo "Missing config file" >&2
+    echo "Missing hook configuration file (${CONF})" >&2
+    exit -1
 fi
 
-REPOSNAME=`echo "$REPOS" | sed -r 's/^.*\/([^\/]+)$/\1/'`
-TRAC_ENV="${TRAC_ENV_PARENT_DIR}/${REPOSNAME}"
-LOGFILE="${TRAC_ENV}/log/svn-precommit.log"
-
-export PYTHONPATH=$TRACPATH
+export PYTHONPATH=$TRACPATH:$GENSHIPATH
+export PYTHON_EGG_CACHE
+export PYTHON=`which python2.5`
 echo "Transaction: $TXN" >> $LOGFILE
-${PYTHON} ${TRACPATH}/hooks/trac-commit-hook \
-    -d "$REPOS" -t "$TXN" -p "$TRAC_ENV" 
+${PYTHON} ${HOOKPATH}/trac-commit-hook -d "$REPOS" -t "$TXN" -p "$TRAC_ENV" 
 RC=$?
 echo "RESULT $RC" >>  $LOGFILE
 [ $RC == 0 ] || exit 1
